platform=iOS
platformVersion=26.3.1
deviceName=iPhone 16e
appPath=/Users/tuyenluu/training-workspace/VTI_AT_202601/UiFramework/apps/wdiodemoapp 2.app
udid=DE460C29-2C9C-405B-913F-A8058180971F
bundleId=